### ISSUE TITLE
NoMethodError when starting rails server

### ISSUE THREAD

**Issue by bhedana** [capistrano/maintenance#14]
using the instructions supplied in the readme results in the following error when starting rails server

/Users/russell/.rvm/gems/ruby-2.0.0-p353@baseapp/bundler/gems/capistrano-maintenance-1b46e54de753/lib/capistrano/tasks/maintenance.rake:1:in `<top (required)>': undefined method `namespace' for main:Object (NoMethodError)

changing the bundler line to require: false fixes this 

  gem 'capistrano-maintenance', github: "capistrano/capistrano-maintenance", require: false

**Comment by trkrameshkumar** [comment]
Thanks @runar , as you commented adding require: false to my Gemfile solves the NoMethodError problem

**Comment by organicweb** [comment]
+1

**Comment by aussiDavid** [comment]
+1
