### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by vincentdebruijn** [capistrano/maintenance#22]
Hi,

There was a previous capistrano-maintenance gem, which worked with Cap 2. It's last version is 0.0.4.

We have many projects and one gemserver. Some projects work with Cap 2 still, some with Cap 3. We packaged this gem for our own gemserver, which is currently at version 0.0.1.

This is now causing problems for us: running bundle update in our Cap 3 projects obtains the older capistrano-maintenance 0.0.4 gem.

For the first release of this gem, we suggest giving it version 0.0.5, because it's newer than the previous capistrano-maintenance gem.

With kind regards,

Vincent de Bruijn

**Comment by mattbrictson** [comment]
capistrano-maintenance is now at 1.0.0. So I think this issue is no longer a problem.
