### ISSUE TITLE
Provide this gem via rubygems.org?

### ISSUE THREAD

**Issue by groe** [capistrano/maintenance#29]
The README suggests to use this gem from Github. However, I noticed that there is a [gem at rubygems.org](https://rubygems.org/gems/capistrano-maintenance) as well. Is this the same gem?

If yes, why is it not recommended in the README to use rubygems? If no, why not? :)

**Comment by RogerE** [comment]
I believe the gem on rubygems is older and for Capistrano 2

**Comment by groe** [comment]
@RogerE is it maintained by the same person?

**Comment by RogerE** [comment]
@groe probably not, you can find a link to the repository at the rubygems.org page you linked to.

**Comment by michaelherold** [comment]
:+1: To this request.

Regarding the question in tydeyen/capistrano-maintence#14 of what to do about naming, what if this were to become `capistrano3-maintenance`, since the README specifically says to use `capistrano ~> 3.0`?

I'd really like to get this git dependency out of my Gemfile.

**Comment by groe** [comment]
@kirs What is your take on that?

**Comment by jrochkind** [comment]
Yes please. Software meant for use should be released to rubygems. 

The README for this repo says "Or install it yourself: $ gem install capistrano-maintenance"

However, if you do that, you get something that claims to be version 0.0.4.  However, this repo has a version file that claims to be 0.0.1.  I don't understand the relationship between the two. Is the actually released one an entirely different codebase that is only for cap2?  Then you're setting people up for confusion. 

If you have or can get rubygems release rights for the "capistrano-maintenance" gem, I recommend releasing this one as 1.0.  If you can not, then you'll have to find another gem name, sure "capistrano3-maintenance" works. 

Pretty please.

**Comment by apolzon** [comment]
At the very least, please update the readme file to reflect the fact that this gem is not the one currently being served by rubygems.

**Comment by jrochkind** [comment]
Okay, if I don't hear otherwise, at some point I'm going to fork this and release it as capistrano3_maintenance. Unless someone else beats me to it, which would be great, because I don't plan to maintain this myself really.

**Comment by groe** [comment]
Let's take one last shot. @kirs (cc @bruno- @leehambley @peterjmit @seenmyfate @swalkinshaw)

**Current status:** This gem is available only via git. An outdated gem with the same name is available via RubyGems. Confusing to everyone.

**Proposed solution:** The maintainer of the RubyGems-gem @tvdeyen is [willing to give access to the gem name](https://github.com/tvdeyen/capistrano-maintenance/issues/14). We can provide this gem via rubygems using the name *capistrano-maintenance*.

**Next Steps:**
1. Increase version number to 1.0.0
2. Kindly ask @tvdeyen to set up access on rubygems
3. Push it to rubygems

Can someone from the capistrano team do that so we can resolve this confusion?

Otherwise we would have to go the fork way.

**Comment by leehambley** [comment]
Either Kirs or I will help you, I'd suggest gem ownership to be transferred to you, and if you're fine with that, I'll set you up with R/W to this repository so you can make the changes you need

**Comment by michaelherold** [comment]
If @groe or @jrochkind don't want the responsibility of maintainership, I can take care of it. It sounds like Jonathan really doesn't want it and I'm not sure about @groe.

**Comment by groe** [comment]
@leehambley Sure, I would be happy to take care of it!

**Comment by tvdeyen** [comment]
Tell me what to do and I will happily transfer ownership of RubyGems and GitHub.

**Comment by kirs** [comment]
Thank you guys and sorry for late reply. It has been the busiest month during last year so far :confused: 

@tvdeyen my RG username is shatrov@me.com. No need to transfer, just add me the `push` access :yellow_heart:

**Comment by tvdeyen** [comment]
@kirs done! I also released a last version (`0.0.5`) of my version that fixes the Capistrano dependency. So now you can publish a `0.1.0` or even a `1.0` release that supports Capistrano 3 \o/

**Comment by kirs** [comment]
@tvdeyen thank you!

I pushed the `1.0.0` version to RG.

**Comment by jrochkind** [comment]
Thank you all! I see you updated the README too, to `gem 'capistrano-maintenance', '~> 1.0'` instead of github direct clone. Thanks!

**Comment by groe** [comment]
Awesome, thank you guys!
