### ISSUE TITLE
Customize template

### ISSUE THREAD

**Issue by vmamaev** [capistrano/maintenance#30]
Could you tell me how I can customize maintenance template?

**Comment by vmamaev** [comment]
maintenance_template_path is solution

**Comment by aussiDavid** [comment]
Could I get a some help with this please

[http://stackoverflow.com/questions/39796970/configure-maintenance-template-path-for-capistrano-maintenace-gem](http://stackoverflow.com/questions/39796970/configure-maintenance-template-path-for-capistrano-maintenace-gem)

Thanks,
